/* =====================================================================
   QUADERNO A QUADRETTI - banca contenuti: FISICA
   Stesso schema di contenuti-matematica.js (vedi il commento in testa
   a quel file per la struttura di argomenti, livelli e item).
   Nei problemi numerici si assume g = 9,8 m/s^2 salvo diversa indicazione.
   ===================================================================== */

window.CONTENUTI_FISICA = [

/* ---------------------------------------------------------------- 1 */
{
  id: "fis1-moto",
  titolo: "Moto, traiettoria e sistema di riferimento",
  sommario: "Le basi della cinematica: descrivere dove si trova un corpo, come si muove e perché la risposta dipende da chi guarda.",
  pillole: [
    {t:"Punto materiale", c:"Per studiare il moto si schematizza spesso il corpo come <strong>punto materiale</strong>: un punto dotato di massa ma privo di dimensioni. È un'approssimazione lecita quando le dimensioni del corpo sono trascurabili rispetto allo spazio percorso - un'auto lungo un'autostrada sì, una porta che ruota sui cardini no."},
    {t:"Sistema di riferimento", c:"Non esiste moto 'in assoluto': serve un <strong>sistema di riferimento</strong>, cioè un corpo di riferimento, un sistema di assi con un'origine, un'unità di misura delle lunghezze e un <em>orologio</em>. Senza questi elementi la domanda 'si sta muovendo?' non ha risposta."},
    {t:"Relatività del moto", c:"Un passeggero seduto sul treno è <em>fermo</em> rispetto al vagone e <em>in moto</em> a 250 km/h rispetto alla stazione: entrambe le affermazioni sono corrette. Anche la <strong>traiettoria</strong> dipende dal riferimento: un sasso lasciato cadere da un treno in corsa descrive un segmento verticale per chi è sul treno e una parabola per chi sta a terra."},
    {t:"Posizione, traiettoria, spostamento", c:"La <strong>posizione</strong> è la coordinata del punto sull'asse (o la coppia/terna di coordinate). La <strong>traiettoria</strong> è la linea disegnata dal punto durante il moto. Lo <strong>spostamento</strong> $\\Delta s=s_2-s_1$ è la variazione di posizione: è una grandezza <em>con segno</em>, diversa dallo <em>spazio percorso</em>, che invece è sempre positivo. Su un giro di pista completo lo spostamento è nullo ma lo spazio percorso è l'intero perimetro."},
    {t:"Velocità media e istantanea", c:"La <strong>velocità media</strong> è $v_m=\\dfrac{\\Delta s}{\\Delta t}$, cioè il rapporto fra spostamento e intervallo di tempo. La <strong>velocità istantanea</strong> è quella misurata in un istante preciso (il tachimetro): coincide con la media solo se il moto è uniforme. Nel SI si misura in m/s; per passare da km/h a m/s si divide per $3{,}6$."},
    {t:"Moto rettilineo uniforme", c:"È il moto su traiettoria rettilinea con velocità costante. La <strong>legge oraria</strong> è $s=s_0+v\\,t$, dove $s_0$ è la posizione iniziale. Percorre spazi uguali in tempi uguali: la relazione fra $s$ e $t$ è di proporzionalità diretta (se $s_0=0$)."},
    {t:"I due grafici del MRU", c:"Nel grafico <strong>spazio-tempo</strong> il MRU è una <em>retta</em>: la sua pendenza è la velocità (più ripida = più veloce; in discesa = velocità negativa, cioè verso opposto). Nel grafico <strong>velocità-tempo</strong> è una retta orizzontale, e l'<em>area</em> sotto di essa misura lo spazio percorso."},
    {t:"Accelerazione (cenno)", c:"Quando la velocità cambia si definisce l'<strong>accelerazione</strong> $a=\\dfrac{\\Delta v}{\\Delta t}$, in m/s$^2$. Nel moto uniformemente accelerato valgono $v=v_0+at$ e $s=s_0+v_0t+\\tfrac{1}{2}at^2$. Se $a$ ha segno opposto a $v$ il moto è <em>decelerato</em>."},
    {t:"Composizione delle velocità", c:"Se un corpo si muove dentro un mezzo a sua volta in movimento (una barca sul fiume, un passeggero che cammina sul treno), le velocità <strong>si sommano vettorialmente</strong>. Nel caso di moti lungo la stessa retta: si sommano se sono concordi, si sottraggono se sono discordi."}
  ],
  formule: [
    {n:"Velocità media", f:"v_m=\\frac{\\Delta s}{\\Delta t}=\\frac{s_2-s_1}{t_2-t_1}"},
    {n:"Legge oraria del MRU", f:"s=s_0+v\\,t"},
    {n:"Conversione km/h - m/s", f:"v_{[\\mathrm{m/s}]}=\\frac{v_{[\\mathrm{km/h}]}}{3{,}6}"},
    {n:"Accelerazione", f:"a=\\frac{\\Delta v}{\\Delta t}"},
    {n:"Moto uniformemente accelerato", f:"s=s_0+v_0t+\\tfrac{1}{2}at^2"}
  ],
  esempi: [
    {t:"Un'auto parte dal km $5$ di una strada e viaggia a $20$ m/s costanti. Dove si trova dopo $30$ s?",
     passi:["Fisso l'origine al km 0 e scrivo la legge oraria: $s=s_0+vt$.",
            "Sostituisco $s_0=5000$ m, $v=20$ m/s, $t=30$ s.",
            "$s=5000+20\\cdot 30=5000+600$."],
     r:"$s=5600$ m, cioè al km $5{,}6$"},
    {t:"Un ciclista percorre $60$ km in $1$ ora all'andata e gli stessi $60$ km in $2$ ore al ritorno. Qual è la velocità media dell'intero viaggio?",
     passi:["La velocità media non è la media delle velocità: si calcola sullo spazio totale e sul tempo totale.",
            "Spazio totale: $60+60=120$ km. Tempo totale: $1+2=3$ h.",
            "$v_m=120:3$."],
     r:"$v_m=40$ km/h (non $45$ km/h)"},
    {t:"Due auto viaggiano nello stesso verso: A parte dall'origine a $20$ m/s, B parte da $100$ m a $15$ m/s. Dopo quanto tempo A raggiunge B?",
     passi:["Scrivo le due leggi orarie: $s_A=20t$ e $s_B=100+15t$.",
            "L'incontro avviene quando $s_A=s_B$: $20t=100+15t$.",
            "Risolvo: $5t=100$."],
     r:"$t=20$ s (nel punto $s=400$ m)"}
  ],
  risorse: [
    {t:"Moto rettilineo uniforme: legge oraria ed esempi", u:"https://www.youmath.it/lezioni/fisica/cinematica/2945-moto-rettilineo-uniforme.html", f:"YouMath"},
    {t:"Grafico spazio-tempo per il MRU", u:"https://www.youmath.it/lezioni/fisica/cinematica/2946-grafici-spazio-tempo-per-il-moto-rettilineo-uniforme.html", f:"YouMath"},
    {t:"Cinematica: lezioni, formule ed esercizi", u:"https://www.youmath.it/lezioni/fisica/cinematica.html", f:"YouMath"},
    {t:"Moto rettilineo uniforme e uniformemente accelerato", u:"https://www.edutecnica.it/meccanica/cine1/cine1.htm", f:"Edutecnica"},
    {t:"50 esercizi risolti sul moto rettilineo", u:"https://www.edutecnica.it/meccanica/cine1x/cine1x.htm", f:"Edutecnica"}
  ],
  livelli: [
    {n:"Livello 1 - Base", d:"Conversioni, velocità media, legge oraria del MRU.", items:[
      {q:"Converti $72$ km/h in metri al secondo.", tipo:"aperta", num:{v:20,u:"m/s",tol:0.001}, sol:["20","20 m/s"],
       spieg:"Si divide per $3{,}6$: $72:3{,}6=20$ m/s. Il fattore nasce da $1$ km $=1000$ m e $1$ h $=3600$ s, quindi $1$ km/h $=1000/3600$ m/s $=1/3{,}6$ m/s."},
      {q:"Un corpo percorre $150$ m in $30$ s. Qual è la sua velocità media in m/s?", tipo:"aperta", num:{v:5,u:"m/s",tol:0.001}, sol:["5","5 m/s"],
       spieg:"$v_m=\\dfrac{\\Delta s}{\\Delta t}=\\dfrac{150}{30}=5$ m/s. È una velocità <em>media</em>: il corpo può aver rallentato e accelerato, ma in media ha coperto 5 metri ogni secondo."},
      {q:"Un corpo in moto rettilineo uniforme viaggia a $4$ m/s. Quanti metri percorre in $12$ s?", tipo:"aperta", num:{v:48,u:"m",tol:0.001}, sol:["48","48 m"],
       spieg:"Nel MRU $s=v\\,t=4\\cdot 12=48$ m. Spazio e tempo sono direttamente proporzionali, con la velocità nel ruolo di costante di proporzionalità."},
      {q:"Quanto tempo impiega un corpo a percorrere $200$ m alla velocità costante di $8$ m/s?", tipo:"aperta", num:{v:25,u:"s",tol:0.001}, sol:["25","25 s"],
       spieg:"Dalla formula inversa $t=\\dfrac{s}{v}=\\dfrac{200}{8}=25$ s. A spazio fissato, tempo e velocità sono inversamente proporzionali."},
      {q:"La <strong>traiettoria</strong> di un corpo è:", tipo:"scelta",
       opz:["la distanza fra partenza e arrivo","la linea descritta dal corpo durante il moto","la velocità con cui si muove","il tempo impiegato"], ok:1,
       spieg:"La traiettoria è la <strong>linea</strong> disegnata dalle posizioni successive del punto materiale. La distanza fra partenza e arrivo è invece il modulo dello spostamento, che in generale è minore della lunghezza della traiettoria."},
      {q:"Quale di questi elementi <strong>non</strong> serve per definire un sistema di riferimento?", tipo:"scelta",
       opz:["un'origine","un orologio","la massa del corpo in moto","un'unità di misura delle lunghezze"], ok:2,
       spieg:"Un sistema di riferimento richiede un corpo di riferimento con origine e assi, un'unità di misura delle lunghezze e un orologio per misurare i tempi. La massa del corpo riguarda la <em>dinamica</em>, non la descrizione cinematica del moto."},
      {q:"Converti $15$ m/s in km/h.", tipo:"aperta", num:{v:54,u:"km/h",tol:0.001}, sol:["54","54 km/h"],
       spieg:"Da m/s a km/h si <strong>moltiplica</strong> per $3{,}6$: $15\\cdot 3{,}6=54$ km/h. Controllo di plausibilità: il numero in km/h deve essere sempre maggiore di quello in m/s."},
      {q:"Nel grafico spazio-tempo, il moto rettilineo uniforme è rappresentato da:", tipo:"scelta",
       opz:["una retta","una parabola","un'iperbole","una retta orizzontale"], ok:0,
       spieg:"Essendo $s=s_0+vt$ una funzione lineare del tempo, il grafico $s$-$t$ è una <strong>retta</strong> la cui pendenza vale $v$. Una retta orizzontale rappresenterebbe un corpo fermo; la parabola è tipica del moto uniformemente accelerato."},
      {q:"Un corpo parte dalla posizione $s_0=10$ m e si muove a $3$ m/s. Dove si trova dopo $5$ s?", tipo:"aperta", num:{v:25,u:"m",tol:0.001}, sol:["25","25 m"],
       spieg:"Legge oraria: $s=s_0+vt=10+3\\cdot 5=10+15=25$ m. Il termine $s_0$ non va dimenticato: indica da dove il corpo è partito rispetto all'origine scelta."},
      {q:"Un passeggero è seduto su un treno in corsa. Rispetto alla stazione egli è:", tipo:"scelta",
       opz:["fermo","in moto","fermo solo se il treno è veloce","non si può dire"], ok:1,
       spieg:"Rispetto alla stazione il passeggero si muove con la velocità del treno; rispetto al vagone è fermo. Non c'è contraddizione: il moto è <strong>relativo</strong> al sistema di riferimento scelto, e nessuno dei due è 'quello giusto'."}
    ]},
    {n:"Livello 2 - Intermedio", d:"Leggi orarie, velocità media su tratti diversi, problemi di incontro.", items:[
      {q:"La legge oraria di un corpo è $s=5+2t$ (in metri e secondi). In quale posizione si trova a $t=8$ s?", tipo:"aperta", num:{v:21,u:"m",tol:0.001}, sol:["21","21 m"],
       spieg:"Sostituisco: $s=5+2\\cdot 8=5+16=21$ m. Il numero $5$ è la posizione iniziale $s_0$, il coefficiente $2$ è la velocità."},
      {q:"Dalla legge oraria $s=5+2t$ (metri, secondi), qual è la velocità del corpo in m/s?", tipo:"aperta", num:{v:2,u:"m/s",tol:0.001}, sol:["2","2 m/s"],
       spieg:"Confrontando con la forma generale $s=s_0+vt$ si riconosce $v=2$ m/s: la velocità è il coefficiente che moltiplica il tempo, cioè la pendenza della retta nel grafico $s$-$t$."},
      {q:"Un ciclista percorre $60$ km in $1$ h all'andata e $60$ km in $2$ h al ritorno. Qual è la velocità media dell'intero viaggio, in km/h?", tipo:"aperta", num:{v:40,u:"km/h",tol:0.001}, sol:["40","40 km/h"],
       spieg:"La velocità media si calcola sempre come spazio totale diviso tempo totale: $\\dfrac{120}{3}=40$ km/h. L'errore classico è fare la media aritmetica di $60$ e $30$, che darebbe $45$ km/h: sbagliato, perché il ciclista ha passato più tempo alla velocità minore."},
      {q:"Un atleta compie un giro completo di una pista di $400$ m. Quanto vale il modulo del suo spostamento, in metri?", tipo:"aperta", num:{v:0,u:"m",tol:0.001}, sol:["0","0 m","zero"],
       spieg:"Lo spostamento è la differenza fra posizione finale e iniziale: tornando al punto di partenza vale <strong>zero</strong>. Lo <em>spazio percorso</em> è invece $400$ m. Distinguere le due grandezze è il punto centrale dell'esercizio."},
      {q:"L'auto A parte dall'origine a $20$ m/s; l'auto B, nello stesso verso, parte da $100$ m a $15$ m/s. Dopo quanti secondi A raggiunge B?", tipo:"aperta", num:{v:20,u:"s",tol:0.001}, sol:["20","20 s"],
       spieg:"Leggi orarie: $s_A=20t$ e $s_B=100+15t$. All'incontro $20t=100+15t$, quindi $5t=100$ e $t=20$ s. Il ragionamento alternativo: A guadagna $5$ m ogni secondo e deve recuperarne $100$."},
      {q:"Nel grafico spazio-tempo, la pendenza della retta rappresenta:", tipo:"scelta",
       opz:["lo spazio percorso","la velocità","l'accelerazione","il tempo impiegato"], ok:1,
       spieg:"La pendenza è $\\dfrac{\\Delta s}{\\Delta t}$, cioè esattamente la definizione di velocità. Una retta più ripida indica un moto più veloce; una retta discendente una velocità negativa, cioè un moto nel verso opposto a quello scelto come positivo."},
      {q:"Un corpo passa dalla posizione $12$ m alla posizione $60$ m in $4$ s. Qual è la sua velocità media in m/s?", tipo:"aperta", num:{v:12,u:"m/s",tol:0.001}, sol:["12","12 m/s"],
       spieg:"$v_m=\\dfrac{60-12}{4}=\\dfrac{48}{4}=12$ m/s. Serve la <strong>differenza</strong> delle posizioni, non la posizione finale: dividere $60$ per $4$ darebbe erroneamente $15$ m/s."},
      {q:"Converti $25$ m/s in km/h.", tipo:"aperta", num:{v:90,u:"km/h",tol:0.001}, sol:["90","90 km/h"],
       spieg:"$25\\cdot 3{,}6=90$ km/h. È la velocità tipica di un'auto in autostrada extraurbana: un buon riferimento per controllare a mente le conversioni."},
      {q:"In quale sistema di riferimento un edificio può essere considerato in moto?", tipo:"scelta",
       opz:["in nessuno: gli edifici sono fermi","in un riferimento solidale con il Sole","solo durante un terremoto","in un riferimento solidale con la Terra"], ok:1,
       spieg:"Rispetto al Sole la Terra - e con essa ogni edificio - si muove a circa $30$ km/s. 'Fermo' e 'in moto' sono sempre affermazioni <strong>relative</strong> a un riferimento: nessuno dei due è privilegiato."},
      {q:"Un corpo ha legge oraria $s=-3+4t$ (metri, secondi). Dopo quanti secondi passa per l'origine?", tipo:"aperta", num:{v:0.75,u:"s",tol:0.001}, sol:["0,75","0.75","0,75 s"],
       spieg:"Passare per l'origine significa $s=0$: $-3+4t=0$, quindi $t=3:4=0{,}75$ s. La posizione iniziale negativa indica che il corpo parte 3 metri prima dell'origine."}
    ]},
    {n:"Livello 3 - Avanzato", d:"Problemi in più passaggi, grafici, composizione delle velocità.", items:[
      {q:"Un'auto viaggia a $90$ km/h e il conducente ha un tempo di reazione di $0{,}8$ s. Quanti metri percorre prima ancora di iniziare a frenare?", tipo:"aperta", num:{v:20,u:"m",tol:0.01}, sol:["20","20 m"],
       spieg:"Durante il tempo di reazione il moto è ancora uniforme. Converto: $90:3{,}6=25$ m/s; poi $s=25\\cdot 0{,}8=20$ m. È lo 'spazio di reazione', che va sommato allo spazio di frenata vero e proprio."},
      {q:"Un treno lungo $200$ m viaggia a $20$ m/s e attraversa una galleria lunga $800$ m. Quanti secondi passano fra l'ingresso della motrice e l'uscita dell'ultima carrozza?", tipo:"aperta", num:{v:50,u:"s",tol:0.01}, sol:["50","50 s"],
       spieg:"Il treno deve percorrere la galleria <strong>più</strong> la propria lunghezza: $800+200=1000$ m. Quindi $t=1000:20=50$ s. Dimenticare la lunghezza del treno è l'errore tipico di questo classico problema."},
      {q:"Due treni distanti $1000$ m viaggiano uno incontro all'altro a $30$ m/s e $20$ m/s. Dopo quanti secondi si incontrano?", tipo:"aperta", num:{v:20,u:"s",tol:0.01}, sol:["20","20 s"],
       spieg:"Muovendosi in verso opposto, la distanza si riduce di $30+20=50$ m ogni secondo (velocità di avvicinamento). Quindi $t=1000:50=20$ s. In alternativa si scrivono le due leggi orarie $s_1=30t$ e $s_2=1000-20t$ e si impone $s_1=s_2$."},
      {q:"Nel grafico velocità-tempo di un MRU, la velocità è $12$ m/s per $10$ s. Quanto vale l'area sotto il grafico, in metri?", tipo:"aperta", num:{v:120,u:"m",tol:0.01}, sol:["120","120 m"],
       spieg:"L'area sotto il grafico $v$-$t$ rappresenta lo <strong>spazio percorso</strong>: qui è un rettangolo di base $10$ s e altezza $12$ m/s, quindi $120$ m. La proprietà vale per qualsiasi moto, non solo per quello uniforme."},
      {q:"Un'auto percorre $30$ km a $60$ km/h e altri $30$ km a $30$ km/h. Qual è la velocità media dell'intero percorso, in km/h?", tipo:"aperta", num:{v:40,u:"km/h",tol:0.01}, sol:["40","40 km/h"],
       spieg:"Primo tratto: $t_1=30:60=0{,}5$ h. Secondo tratto: $t_2=30:30=1$ h. Totale: $60$ km in $1{,}5$ h, quindi $v_m=40$ km/h. Anche qui la media aritmetica ($45$) sarebbe sbagliata."},
      {q:"Qual è la differenza fra velocità media e velocità istantanea?", tipo:"scelta",
       opz:["nessuna: sono sinonimi","la media si riferisce a un intervallo di tempo, l'istantanea a un singolo istante","la media si misura in km/h e l'istantanea in m/s","l'istantanea vale solo nel moto uniforme"], ok:1,
       spieg:"La velocità media riassume un intero intervallo con un unico numero; quella istantanea è il valore in un preciso istante, cioè ciò che indica il tachimetro. Coincidono <em>solo</em> se il moto è uniforme."},
      {q:"Un ciclista viaggia a $8$ m/s per $5$ minuti. Quanti metri percorre?", tipo:"aperta", num:{v:2400,u:"m",tol:0.01}, sol:["2400","2400 m"],
       spieg:"Prima si uniformano le unità: $5$ min $=300$ s. Poi $s=8\\cdot 300=2400$ m, cioè $2{,}4$ km. Usare i minuti al posto dei secondi darebbe un risultato sbagliato di un fattore 60."},
      {q:"Un sasso viene lasciato cadere dal finestrino di un treno in corsa. Per un osservatore fermo a terra, la traiettoria del sasso è:", tipo:"scelta",
       opz:["un segmento verticale","una parabola","una retta orizzontale","una circonferenza"], ok:1,
       spieg:"Per il passeggero il sasso cade verticalmente; per l'osservatore a terra il sasso conserva anche la velocità orizzontale del treno, quindi descrive una <strong>parabola</strong>. È la prova più chiara che la traiettoria dipende dal sistema di riferimento."},
      {q:"Un corpo ha legge oraria $s=2+6t$ (metri, secondi). Dopo quanti secondi si trova a $50$ m dall'origine?", tipo:"aperta", num:{v:8,u:"s",tol:0.01}, sol:["8","8 s"],
       spieg:"Impongo $2+6t=50$: $6t=48$, quindi $t=8$ s. È il problema inverso rispetto al calcolo della posizione a un istante dato."},
      {q:"Una barca si muove a $5$ m/s rispetto all'acqua di un fiume che scorre a $2$ m/s. Qual è la velocità della barca rispetto alla riva se procede nel verso della corrente?", tipo:"aperta", num:{v:7,u:"m/s",tol:0.01}, sol:["7","7 m/s"],
       spieg:"Le velocità sono concordi, quindi si sommano: $5+2=7$ m/s. Risalendo la corrente sarebbero discordi e la velocità rispetto alla riva sarebbe $5-2=3$ m/s. È la legge di composizione delle velocità in una dimensione."}
    ]}
  ]
},

/* ---------------------------------------------------------------- 2 */
{
  id: "fis1-attrito",
  titolo: "Attrito",
  sommario: "Attrito radente statico e dinamico, coefficienti, forza normale e applicazioni: frenata, piano inclinato, moto a velocità costante.",
  pillole: [
    {t:"Che cos'è l'attrito", c:"L'<strong>attrito</strong> è la forza che si oppone al moto relativo (o alla tendenza al moto) fra due superfici a contatto. Nasce dalle irregolarità microscopiche e dalle interazioni fra le superfici. La sua direzione è <em>parallela</em> alle superfici e il verso è sempre <strong>opposto</strong> al moto (o al moto tentato)."},
    {t:"Forza normale", c:"La <strong>forza normale</strong> $N$ è la reazione perpendicolare che la superficie esercita sul corpo. Su un piano orizzontale, in assenza di altre forze verticali, $N=mg$. Su un piano inclinato di angolo $\\theta$ vale invece $N=mg\\cos\\theta$: è minore, ed è il motivo per cui su una discesa si slitta più facilmente."},
    {t:"Attrito statico", c:"Finché il corpo è fermo, l'attrito statico <em>si adatta</em> alla forza applicata e la equilibra esattamente. Ha però un valore massimo: $F_{s,max}=\\mu_s N$. Superato quel valore il corpo si mette in moto. Quindi $F_s\\le\\mu_s N$: è una disuguaglianza, non un'uguaglianza."},
    {t:"Attrito dinamico", c:"Quando il corpo striscia, l'attrito dinamico vale $F_d=\\mu_d N$ e non dipende (in prima approssimazione) dalla velocità. Si ha sempre $\\mu_d<\\mu_s$: per questo è più faticoso mettere in movimento un mobile che continuare a spingerlo."},
    {t:"I coefficienti", c:"$\\mu_s$ e $\\mu_d$ sono numeri <strong>adimensionali</strong> (senza unità di misura) che dipendono dalla coppia di materiali e dallo stato delle superfici. Valori indicativi: acciaio su acciaio $\\approx 0{,}6$; gomma su asfalto asciutto $\\approx 0{,}8$; gomma su asfalto bagnato $\\approx 0{,}4$; ghiaccio su ghiaccio $\\approx 0{,}1$."},
    {t:"Indipendenza dall'area", c:"Un risultato controintuitivo ma sperimentale: la forza di attrito radente <strong>non dipende dall'area</strong> apparente di contatto. Raddoppiando l'area si dimezza la pressione, e i due effetti si compensano. Dipende solo dai materiali ($\\mu$) e dalla forza normale ($N$)."},
    {t:"Altri tipi di attrito", c:"L'<strong>attrito volvente</strong> (rotolamento) è molto minore di quello radente: è la ragione dell'invenzione della ruota e dei cuscinetti a sfere. L'<strong>attrito viscoso</strong> nei fluidi cresce invece con la velocità, ed è ciò che determina la velocità limite di un paracadutista."},
    {t:"L'attrito non è solo un ostacolo", c:"Senza attrito non si potrebbe camminare, un'auto non potrebbe accelerare né frenare, un chiodo non terrebbe. La spinta che ci fa avanzare è proprio la reazione d'attrito del suolo sulla suola."},
    {t:"Corpo a velocità costante", c:"Se un corpo viene trascinato a <strong>velocità costante</strong>, l'accelerazione è nulla e quindi la forza applicata eguaglia esattamente l'attrito dinamico: $F=\\mu_d N$. È il modo sperimentale più semplice per misurare $\\mu_d$ con un dinamometro."}
  ],
  formule: [
    {n:"Attrito statico massimo", f:"F_{s,max}=\\mu_s N"},
    {n:"Attrito dinamico", f:"F_d=\\mu_d N"},
    {n:"Forza normale su piano orizzontale", f:"N=mg"},
    {n:"Forza normale su piano inclinato", f:"N=mg\\cos\\theta"},
    {n:"Secondo principio con attrito", f:"F-\\mu_d N=ma"}
  ],
  esempi: [
    {t:"Una cassa di $20$ kg è ferma su un pavimento con $\\mu_s=0{,}5$. Quale forza orizzontale minima serve per metterla in movimento? ($g=9{,}8$ m/s$^2$)",
     passi:["Calcolo la forza normale: $N=mg=20\\cdot 9{,}8=196$ N.",
            "Calcolo l'attrito statico massimo: $F_{s,max}=\\mu_s N=0{,}5\\cdot 196$.",
            "Per mettere in moto la cassa bisogna superare questo valore."],
     r:"$98$ N"},
    {t:"Un blocco di $10$ kg è tirato con una forza orizzontale di $50$ N su un piano con $\\mu_d=0{,}2$. Qual è la sua accelerazione?",
     passi:["Forza normale: $N=mg=10\\cdot 9{,}8=98$ N.",
            "Attrito dinamico: $F_d=0{,}2\\cdot 98=19{,}6$ N.",
            "Forza risultante: $F_{ris}=50-19{,}6=30{,}4$ N.",
            "Secondo principio: $a=F_{ris}/m=30{,}4/10$."],
     r:"$a\\approx 3{,}04$ m/s$^2$"},
    {t:"Un'auto a $20$ m/s frena su asfalto asciutto con $\\mu_d=0{,}8$. Qual è lo spazio di frenata?",
     passi:["La decelerazione dovuta al solo attrito è $a=\\mu_d g=0{,}8\\cdot 9{,}8=7{,}84$ m/s$^2$.",
            "Uso la relazione $v^2=2as$, cioè $s=\\dfrac{v^2}{2a}$.",
            "$s=\\dfrac{400}{2\\cdot 7{,}84}=\\dfrac{400}{15{,}68}$."],
     r:"$s\\approx 25{,}5$ m"}
  ],
  risorse: [
    {t:"Forza d'attrito radente: statico e dinamico", u:"https://www.youmath.it/lezioni/fisica/dinamica/2968-attrito-radente-statico-dinamico.html", f:"YouMath"},
    {t:"Coefficiente di attrito statico e dinamico: valori", u:"https://www.youmath.it/domande-a-risposte/view/3391-coefficiente-di-attrito-statico-dinamico.html", f:"YouMath"},
    {t:"Piano inclinato con attrito: formule e diagramma delle forze", u:"https://www.youmath.it/lezioni/fisica/dinamica/2970-il-piano-inclinato-con-attrito.html", f:"YouMath"},
    {t:"Principi della dinamica", u:"https://www.edutecnica.it/meccanica/dina1/dina1.htm", f:"Edutecnica"},
    {t:"Formulario di dinamica", u:"https://www.youmath.it/lezioni/fisica/dinamica/3701-formule-dinamica.html", f:"YouMath"}
  ],
  livelli: [
    {n:"Livello 1 - Base", d:"Applicazione diretta di $F=\\mu N$ e calcolo della forza normale.", items:[
      {q:"Un corpo preme su un piano con forza normale $N=200$ N e il coefficiente di attrito dinamico è $\\mu_d=0{,}3$. Quanto vale la forza di attrito, in newton?", tipo:"aperta", num:{v:60,u:"N",tol:0.01}, sol:["60","60 N"],
       spieg:"$F_d=\\mu_d N=0{,}3\\cdot 200=60$ N. Il coefficiente è un numero puro, quindi il risultato ha le stesse unità della forza normale."},
      {q:"Un corpo di massa $5$ kg è appoggiato su un piano orizzontale. Quanto vale la forza normale, in newton? ($g=9{,}8$ m/s$^2$)", tipo:"aperta", num:{v:49,u:"N",tol:0.01}, sol:["49","49 N"],
       spieg:"Su un piano orizzontale, senza altre forze verticali, la normale equilibra il peso: $N=mg=5\\cdot 9{,}8=49$ N. Su un piano inclinato sarebbe minore, perché varrebbe $mg\\cos\\theta$."},
      {q:"Con $\\mu_s=0{,}4$ e $N=100$ N, quanto vale la massima forza di attrito statico, in newton?", tipo:"aperta", num:{v:40,u:"N",tol:0.01}, sol:["40","40 N"],
       spieg:"$F_{s,max}=\\mu_s N=0{,}4\\cdot 100=40$ N. Applicando una forza minore il corpo resta fermo (l'attrito si adegua); superando i 40 N comincia a scivolare."},
      {q:"Fra i coefficienti di attrito statico e dinamico vale di regola:", tipo:"scelta",
       opz:["$\\mu_s=\\mu_d$","$\\mu_s>\\mu_d$","$\\mu_s<\\mu_d$","dipende dalla velocità"], ok:1,
       spieg:"Il coefficiente statico è maggiore di quello dinamico. Conseguenza pratica: serve più forza per <em>avviare</em> il movimento di un mobile che per mantenerlo, e infatti appena parte si ha la sensazione che diventi improvvisamente più leggero."},
      {q:"La forza di attrito radente dipende dall'area della superficie di contatto?", tipo:"scelta",
       opz:["Sì, cresce con l'area","No, dipende solo da $\\mu$ e da $N$","Sì, diminuisce con l'area","Solo per i corpi molto pesanti"], ok:1,
       spieg:"No: aumentando l'area diminuisce la pressione, e i due effetti si compensano. La forza di attrito radente dipende soltanto dai materiali (tramite $\\mu$) e dalla forza normale $N$."},
      {q:"Un corpo con $N=125$ N subisce una forza di attrito dinamico di $25$ N. Quanto vale $\\mu_d$?", tipo:"aperta", num:{v:0.2,tol:0.001}, sol:["0,2","0.2"],
       spieg:"Dalla formula inversa: $\\mu_d=\\dfrac{F_d}{N}=\\dfrac{25}{125}=0{,}2$. Il coefficiente è <strong>adimensionale</strong>: è un rapporto fra due forze, quindi non ha unità di misura."},
      {q:"La forza di attrito ha direzione e verso:", tipo:"scelta",
       opz:["perpendicolare alla superficie, verso l'alto","parallela alla superficie, opposta al moto","parallela alla superficie, concorde al moto","sempre verticale verso il basso"], ok:1,
       spieg:"L'attrito radente è <strong>parallelo</strong> alle superfici a contatto e ha verso <strong>opposto</strong> al moto (o al moto tentato). La forza perpendicolare alla superficie è invece la reazione normale $N$."},
      {q:"Un corpo di $10$ kg striscia su un piano orizzontale con $\\mu_d=0{,}25$. Quanto vale la forza di attrito, in newton? ($g=9{,}8$)", tipo:"aperta", num:{v:24.5,u:"N",tol:0.01}, sol:["24,5","24.5","24,5 N"],
       spieg:"Prima la normale: $N=mg=98$ N. Poi $F_d=0{,}25\\cdot 98=24{,}5$ N. Il passaggio attraverso $N$ è obbligatorio: moltiplicare $\\mu$ per la massa non avrebbe senso dimensionale."},
      {q:"Quale di questi <strong>non</strong> è un tipo di attrito?", tipo:"scelta",
       opz:["radente","volvente","viscoso","normale"], ok:3,
       spieg:"'Normale' non è un tipo di attrito: è il nome della reazione vincolare perpendicolare alla superficie. I tre tipi di attrito sono radente (strisciamento), volvente (rotolamento) e viscoso (moto nei fluidi)."},
      {q:"Se $N=80$ N e la forza di attrito dinamico è $12$ N, quanto vale $\\mu_d$?", tipo:"aperta", num:{v:0.15,tol:0.001}, sol:["0,15","0.15"],
       spieg:"$\\mu_d=\\dfrac{12}{80}=0{,}15$. Un valore basso, tipico di superfici piuttosto lisce o lubrificate."}
    ]},
    {n:"Livello 2 - Intermedio", d:"Attrito combinato con il secondo principio, misura sperimentale di $\\mu$.", items:[
      {q:"Quale forza orizzontale minima serve per mettere in moto una cassa di $20$ kg con $\\mu_s=0{,}5$? (in newton, $g=9{,}8$)", tipo:"aperta", num:{v:98,u:"N",tol:0.05}, sol:["98","98 N"],
       spieg:"$N=mg=196$ N, quindi $F_{s,max}=0{,}5\\cdot 196=98$ N. Occorre superare (anche di pochissimo) questo valore: finché la forza applicata resta sotto, l'attrito statico la equilibra e la cassa non si muove."},
      {q:"Un blocco di $10$ kg è tirato con $50$ N su un piano con $\\mu_d=0{,}2$. Qual è la sua accelerazione in m/s$^2$? ($g=9{,}8$)", tipo:"aperta", num:{v:3.04,u:"m/s^2",tol:0.02}, sol:["3,04","3.04"],
       spieg:"$N=98$ N; $F_d=0{,}2\\cdot 98=19{,}6$ N; risultante $50-19{,}6=30{,}4$ N; quindi $a=30{,}4/10=3{,}04$ m/s$^2$. Il secondo principio va applicato alla forza <strong>risultante</strong>, non a quella applicata."},
      {q:"Perché il coefficiente di attrito statico è maggiore di quello dinamico?", tipo:"scelta",
       opz:["perché a riposo le superfici hanno più tempo per 'incastrarsi' fra loro","perché la massa aumenta quando il corpo è fermo","perché la forza normale è maggiore a riposo","perché l'attrito statico dipende dalla velocità"], ok:0,
       spieg:"A contatto prolungato le microasperità e i legami fra le superfici si assestano e devono essere 'rotti' per avviare il moto; una volta in movimento il contatto è meno intimo. Massa e forza normale non cambiano affatto."},
      {q:"Su una cassa ferma ($\\mu_s N=45$ N) viene applicata una forza orizzontale di $30$ N. Quanto vale in quel momento la forza di attrito, in newton?", tipo:"aperta", num:{v:30,u:"N",tol:0.01}, sol:["30","30 N"],
       spieg:"La cassa resta ferma, quindi la risultante deve essere nulla: l'attrito statico vale esattamente $30$ N, cioè <strong>si adatta</strong> alla forza applicata. Il valore $45$ N è solo il massimo disponibile, non quello effettivamente in gioco."},
      {q:"Un corpo di $4$ kg striscia su un piano con $\\mu_d=0{,}35$. Quanto vale l'attrito, in newton? ($g=9{,}8$)", tipo:"aperta", num:{v:13.72,u:"N",tol:0.02}, sol:["13,72","13.72"],
       spieg:"$N=4\\cdot 9{,}8=39{,}2$ N; $F_d=0{,}35\\cdot 39{,}2=13{,}72$ N."},
      {q:"Un corpo lanciato su un piano orizzontale decelera a $2$ m/s$^2$ per solo effetto dell'attrito. Quanto vale $\\mu_d$? ($g=9{,}8$)", tipo:"aperta", num:{v:0.204,tol:0.005}, sol:["0,20","0.20","0,204"],
       spieg:"L'unica forza orizzontale è l'attrito: $ma=\\mu_d mg$, e la massa si semplifica. Quindi $\\mu_d=\\dfrac{a}{g}=\\dfrac{2}{9{,}8}\\approx 0{,}20$. Il fatto che la massa sparisca è il punto interessante: la decelerazione non dipende da quanto è pesante il corpo."},
      {q:"L'attrito volvente (di rotolamento) rispetto a quello radente è:", tipo:"scelta",
       opz:["molto maggiore","circa uguale","molto minore","nullo"], ok:2,
       spieg:"È molto minore: per questo si usano ruote, rulli e cuscinetti a sfere. Trasformare uno strisciamento in un rotolamento è uno dei modi più efficaci per ridurre le perdite per attrito."},
      {q:"Su un corpo con $N=300$ N agisce un attrito di $60$ N. Se la forza normale raddoppia, quanto vale il nuovo attrito, in newton?", tipo:"aperta", num:{v:120,u:"N",tol:0.01}, sol:["120","120 N"],
       spieg:"$F_d=\\mu_d N$ è una proporzionalità <strong>diretta</strong>: raddoppiando $N$ raddoppia anche $F_d$, quindi $120$ N. ($\\mu_d=60/300=0{,}2$ resta invariato perché dipende solo dai materiali.)"},
      {q:"In quale di queste situazioni l'attrito è <strong>utile</strong>?", tipo:"scelta",
       opz:["nel motore di un'auto, fra pistone e cilindro","nella frenata di una bicicletta","nei cuscinetti di un albero rotante","nel trasporto di merci su rulli"], ok:1,
       spieg:"Senza attrito fra pattino e cerchione (e fra pneumatico e asfalto) la bicicletta non potrebbe fermarsi. Negli altri tre casi l'attrito è invece una perdita da ridurre con lubrificanti o cuscinetti."},
      {q:"Un corpo di $2{,}5$ kg ha $\\mu_s=0{,}6$. Qual è la massima forza orizzontale che si può applicare senza muoverlo, in newton? ($g=9{,}8$)", tipo:"aperta", num:{v:14.7,u:"N",tol:0.02}, sol:["14,7","14.7"],
       spieg:"$N=2{,}5\\cdot 9{,}8=24{,}5$ N; $F_{s,max}=0{,}6\\cdot 24{,}5=14{,}7$ N. Fino a questo valore il corpo resta fermo."}
    ]},
    {n:"Livello 3 - Avanzato", d:"Frenata, piano inclinato, ragionamenti su leggi quadratiche.", items:[
      {q:"Un corpo di $12$ kg è spinto orizzontalmente con $60$ N su un piano con $\\mu_d=0{,}3$. Qual è la sua accelerazione in m/s$^2$? ($g=9{,}8$)", tipo:"aperta", num:{v:2.06,u:"m/s^2",tol:0.03}, sol:["2,06","2.06"],
       spieg:"$N=12\\cdot 9{,}8=117{,}6$ N; $F_d=0{,}3\\cdot 117{,}6=35{,}28$ N; risultante $60-35{,}28=24{,}72$ N; $a=24{,}72/12\\approx 2{,}06$ m/s$^2$."},
      {q:"Un'auto a $20$ m/s frena con $\\mu_d=0{,}8$. Qual è lo spazio di frenata in metri? ($g=9{,}8$)", tipo:"aperta", num:{v:25.5,u:"m",tol:0.3}, sol:["25,5","25.5","25,51"],
       spieg:"Decelerazione: $a=\\mu_d g=7{,}84$ m/s$^2$. Dalla relazione $v^2=2as$ si ricava $s=\\dfrac{v^2}{2a}=\\dfrac{400}{15{,}68}\\approx 25{,}5$ m. A questi vanno sommati i metri percorsi durante il tempo di reazione."},
      {q:"Un corpo è sul punto di scivolare su un piano inclinato di $30^\\circ$. Quanto vale il coefficiente di attrito statico?", tipo:"aperta", num:{v:0.577,tol:0.01}, sol:["0,577","0.577","0,58"],
       spieg:"All'equilibrio limite la componente del peso lungo il piano eguaglia l'attrito massimo: $mg\\sin\\theta=\\mu_s\\,mg\\cos\\theta$. La massa e $g$ si semplificano e resta $\\mu_s=\\tan\\theta=\\tan 30^\\circ\\approx 0{,}577$. L'angolo limite misura direttamente il coefficiente."},
      {q:"A che cosa serve il sistema ABS su un'automobile?", tipo:"scelta",
       opz:["ad aumentare il coefficiente di attrito degli pneumatici","a impedire il bloccaggio delle ruote, mantenendo l'attrito statico invece di quello dinamico","ad aumentare la massa dell'auto in frenata","a eliminare del tutto l'attrito"], ok:1,
       spieg:"Con le ruote bloccate lo pneumatico striscia e agisce il coefficiente <strong>dinamico</strong>, minore; l'ABS impedisce il bloccaggio così che la ruota continui a rotolare e resti in regime di attrito <strong>statico</strong>, più elevato. Si frena di più e si mantiene la direzionalità."},
      {q:"Un corpo di $6$ kg è su un piano inclinato di $20^\\circ$. Quanto vale la componente del peso parallela al piano, in newton? ($g=9{,}8$)", tipo:"aperta", num:{v:20.1,u:"N",tol:0.3}, sol:["20,1","20.1","20"],
       spieg:"La componente parallela è $mg\\sin\\theta=6\\cdot 9{,}8\\cdot\\sin 20^\\circ=58{,}8\\cdot 0{,}342\\approx 20{,}1$ N. È questa la componente che tende a far scivolare il corpo; quella perpendicolare, $mg\\cos\\theta$, determina invece la forza normale."},
      {q:"Un corpo lanciato a $15$ m/s si ferma per solo attrito con $\\mu_d=0{,}5$. Dopo quanti secondi si arresta? ($g=9{,}8$)", tipo:"aperta", num:{v:3.06,u:"s",tol:0.05}, sol:["3,06","3.06","3,1"],
       spieg:"Decelerazione $a=\\mu_d g=4{,}9$ m/s$^2$; dalla legge $v=v_0-at$ con $v=0$ si ha $t=\\dfrac{v_0}{a}=\\dfrac{15}{4{,}9}\\approx 3{,}06$ s."},
      {q:"L'attrito <strong>viscoso</strong> si distingue da quello radente perché:", tipo:"scelta",
       opz:["non dipende dai materiali","dipende dalla velocità del corpo","è sempre maggiore","agisce solo sui corpi fermi"], ok:1,
       spieg:"L'attrito nei fluidi cresce con la velocità (in modo lineare a basse velocità, quadratico ad alte). È il motivo per cui un paracadutista raggiunge una <em>velocità limite</em>: quando la resistenza eguaglia il peso, l'accelerazione si annulla."},
      {q:"Una slitta di $30$ kg viene trainata a velocità costante da una forza orizzontale di $90$ N. Quanto vale $\\mu_d$? ($g=9{,}8$)", tipo:"aperta", num:{v:0.306,tol:0.01}, sol:["0,306","0.306","0,31"],
       spieg:"Velocità costante significa accelerazione nulla, quindi la forza applicata eguaglia l'attrito: $\\mu_d=\\dfrac{F}{mg}=\\dfrac{90}{294}\\approx 0{,}31$. È il metodo sperimentale standard per misurare $\\mu_d$ con un dinamometro."},
      {q:"Su un piano inclinato di angolo $\\theta$, la forza normale vale:", tipo:"scelta",
       opz:["$mg$","$mg\\sin\\theta$","$mg\\cos\\theta$","$mg\\tan\\theta$"], ok:2,
       spieg:"Il peso si scompone in una componente parallela al piano ($mg\\sin\\theta$, che tende a far scivolare il corpo) e una perpendicolare ($mg\\cos\\theta$, equilibrata dalla reazione normale). Quindi $N=mg\\cos\\theta$: è minore di $mg$, e cala all'aumentare della pendenza."},
      {q:"Se la velocità di un'auto raddoppia, lo spazio di frenata (a parità di attrito):", tipo:"scelta",
       opz:["raddoppia","quadruplica","resta uguale","si dimezza"], ok:1,
       spieg:"Da $s=\\dfrac{v^2}{2a}$ si vede che lo spazio dipende dal <strong>quadrato</strong> della velocità: raddoppiando $v$ lo spazio diventa quattro volte più grande. È una proporzionalità quadratica, e la ragione fisica dei limiti di velocità."}
    ]}
  ]
},

/* ---------------------------------------------------------------- 3 */
{
  id: "fis1-hooke",
  titolo: "Legge di Hooke e forza elastica",
  sommario: "La molla come modello di forza di richiamo: costante elastica, allungamento, dinamometro, molle in serie e in parallelo.",
  pillole: [
    {t:"La legge di Hooke", c:"Entro il limite di elasticità, la forza esercitata da una molla è <strong>direttamente proporzionale</strong> alla deformazione: $F=-kx$, dove $x$ è l'allungamento (o la compressione) rispetto alla lunghezza a riposo. Il segno meno indica che la forza è <em>di richiamo</em>: è sempre diretta verso la posizione di equilibrio, opposta allo spostamento."},
    {t:"La costante elastica", c:"$k$ si misura in <strong>newton al metro (N/m)</strong> e rappresenta la 'rigidità' della molla: quanti newton servono per allungarla di un metro. Molla <em>rigida</em> = $k$ grande e allungamento piccolo; molla <em>morbida</em> = $k$ piccolo. A parità di forza, la molla con $k$ minore si allunga di più."},
    {t:"Attenzione alle unità", c:"Nella formula $F=kx$ l'allungamento va espresso in <strong>metri</strong>, non in centimetri. Un errore di conversione porta a sbagliare di un fattore 100. Conviene convertire subito tutti i dati nel SI prima di sostituire."},
    {t:"Il grafico F-x", c:"Riportando la forza in funzione dell'allungamento si ottiene una <strong>retta passante per l'origine</strong> la cui pendenza è proprio $k$. È l'esempio più limpido di proporzionalità diretta in fisica, e permette di misurare $k$ sperimentalmente dal grafico."},
    {t:"Limite di elasticità", c:"La legge vale solo entro un certo intervallo. Superato il <strong>limite di elasticità</strong>, la molla non torna più alla lunghezza iniziale (deformazione <em>plastica</em>) e, oltre il carico di rottura, si spezza. Fuori da quel campo il grafico $F$-$x$ smette di essere una retta."},
    {t:"Il dinamometro", c:"È lo strumento che misura le forze sfruttando la legge di Hooke: si legge l'allungamento della molla e lo si converte in forza. La <em>portata</em> (fondo scala) è la massima forza misurabile senza superare il limite di elasticità, la <em>sensibilità</em> la minima variazione apprezzabile."},
    {t:"Molla verticale con massa appesa", c:"Appendendo una massa $m$, all'equilibrio la forza elastica equilibra il peso: $kx=mg$, quindi $x=\\dfrac{mg}{k}$. È il principio di taratura di ogni dinamometro a molla."},
    {t:"Molle in serie e in parallelo", c:"In <strong>parallelo</strong> (affiancate, che si allungano insieme) le costanti si sommano: $k_{eq}=k_1+k_2$, il sistema è più rigido. In <strong>serie</strong> (una di seguito all'altra) si sommano i reciproci: $\\dfrac{1}{k_{eq}}=\\dfrac{1}{k_1}+\\dfrac{1}{k_2}$, il sistema è più cedevole. Con due molle uguali $k$: parallelo $2k$, serie $k/2$."},
    {t:"Energia elastica", c:"Il lavoro compiuto per deformare la molla si immagazzina come <strong>energia potenziale elastica</strong> $E=\\tfrac{1}{2}kx^2$, in joule. Dipende dal <em>quadrato</em> dell'allungamento: raddoppiando $x$ l'energia quadruplica. È l'area del triangolo sotto il grafico $F$-$x$."}
  ],
  formule: [
    {n:"Legge di Hooke", f:"F=-kx \\qquad (\\text{in modulo } F=kx)"},
    {n:"Costante elastica", f:"k=\\frac{F}{x} \\quad [\\mathrm{N/m}]"},
    {n:"Massa appesa in equilibrio", f:"x=\\frac{mg}{k}"},
    {n:"Molle in parallelo / serie", f:"k_{eq}=k_1+k_2 \\qquad \\frac{1}{k_{eq}}=\\frac{1}{k_1}+\\frac{1}{k_2}"},
    {n:"Energia potenziale elastica", f:"E=\\tfrac{1}{2}kx^2"}
  ],
  esempi: [
    {t:"Una molla si allunga di $4$ cm quando si applica una forza di $2$ N. Qual è la sua costante elastica?",
     passi:["Converto l'allungamento nel SI: $4$ cm $=0{,}04$ m.",
            "Applico la formula inversa: $k=\\dfrac{F}{x}=\\dfrac{2}{0{,}04}$."],
     r:"$k=50$ N/m"},
    {t:"Di quanto si allunga la stessa molla ($k=50$ N/m) applicando una forza di $5$ N?",
     passi:["Uso $x=\\dfrac{F}{k}=\\dfrac{5}{50}$.",
            "Converto in centimetri per leggibilità: $0{,}1$ m $=10$ cm."],
     r:"$x=0{,}1$ m $=10$ cm"},
    {t:"Una molla di costante $k=200$ N/m viene allungata di $10$ cm. Quanta energia elastica immagazzina?",
     passi:["Converto: $x=0{,}10$ m.",
            "Applico $E=\\tfrac{1}{2}kx^2=\\tfrac{1}{2}\\cdot 200\\cdot 0{,}01$."],
     r:"$E=1$ J"}
  ],
  risorse: [
    {t:"Forza elastica e legge di Hooke", u:"https://www.youmath.it/lezioni/fisica/dinamica/2971-forza-elastica-legge-di-hooke.html", f:"YouMath"},
    {t:"Lavoro della forza elastica", u:"https://www.youmath.it/lezioni/fisica/dinamica/2981-lavoro-della-forza-elastica.html", f:"YouMath"},
    {t:"Dinamica: lezioni, formule ed esercizi", u:"https://www.youmath.it/lezioni/fisica/dinamica.html", f:"YouMath"},
    {t:"Moto armonico semplice (approfondimento)", u:"https://www.edutecnica.it/meccanica/shm/shm.htm", f:"Edutecnica"}
  ],
  livelli: [
    {n:"Livello 1 - Base", d:"Applicazione diretta di $F=kx$ e delle sue formule inverse.", items:[
      {q:"Una molla ha $k=200$ N/m e viene allungata di $0{,}05$ m. Quanto vale la forza elastica, in newton?", tipo:"aperta", num:{v:10,u:"N",tol:0.01}, sol:["10","10 N"],
       spieg:"$F=kx=200\\cdot 0{,}05=10$ N. Il segno meno della formula indica solo il verso (di richiamo): in modulo la forza vale $10$ N."},
      {q:"Una forza di $15$ N allunga una molla di $0{,}03$ m. Quanto vale la costante elastica, in N/m?", tipo:"aperta", num:{v:500,u:"N/m",tol:0.5}, sol:["500","500 N/m"],
       spieg:"$k=\\dfrac{F}{x}=\\dfrac{15}{0{,}03}=500$ N/m. Un valore piuttosto alto: servono 500 N per allungarla di un metro, quindi è una molla rigida."},
      {q:"Una molla con $k=250$ N/m è sottoposta a una forza di $20$ N. Di quanti metri si allunga?", tipo:"aperta", num:{v:0.08,u:"m",tol:0.001}, sol:["0,08","0.08","0,08 m"],
       spieg:"Si usa la formula inversa della legge di Hooke: $x=\\dfrac{F}{k}=\\dfrac{20}{250}=0{,}08$ m, cioè $8$ cm. Il risultato è in metri perché $k$ è espressa in N/m: dividendo newton per newton al metro restano i metri."},
      {q:"Nella legge $F=-kx$ il segno meno indica che:", tipo:"scelta",
       opz:["la forza è sempre negativa","la forza è opposta allo spostamento, cioè di richiamo","la molla è compressa","la costante elastica è negativa"], ok:1,
       spieg:"Il segno meno dice che la forza elastica è sempre diretta <strong>verso la posizione di equilibrio</strong>, in verso opposto alla deformazione: se allunghi tira indietro, se comprimi spinge in fuori. La costante $k$ è invece sempre positiva."},
      {q:"A una molla con $k=100$ N/m si appende una massa di $0{,}5$ kg. Di quanti metri si allunga? ($g=9{,}8$)", tipo:"aperta", num:{v:0.049,u:"m",tol:0.001}, sol:["0,049","0.049"],
       spieg:"All'equilibrio la forza elastica equilibra il peso: $kx=mg$, quindi $x=\\dfrac{0{,}5\\cdot 9{,}8}{100}=\\dfrac{4{,}9}{100}=0{,}049$ m, cioè $4{,}9$ cm."},
      {q:"Qual è l'unità di misura della costante elastica nel Sistema Internazionale?", tipo:"scelta",
       opz:["N (newton)","N/m (newton al metro)","m/N","J (joule)"], ok:1,
       spieg:"Da $k=F/x$ segue che l'unità è newton diviso metri: <strong>N/m</strong>. Rappresenta la forza necessaria per produrre un allungamento di un metro."},
      {q:"Una molla con $k=80$ N/m viene allungata di $0{,}25$ m. Quanto vale la forza, in newton?", tipo:"aperta", num:{v:20,u:"N",tol:0.01}, sol:["20","20 N"],
       spieg:"$F=kx=80\\cdot 0{,}25=20$ N. L'allungamento è già espresso in metri, quindi si sostituisce direttamente; se fosse stato dato in centimetri ($25$ cm) sarebbe stato necessario convertirlo prima."},
      {q:"Il grafico della forza elastica in funzione dell'allungamento è:", tipo:"scelta",
       opz:["una retta passante per l'origine","una parabola","un'iperbole","una retta orizzontale"], ok:0,
       spieg:"$F=kx$ è una proporzionalità diretta, quindi il grafico è una <strong>retta per l'origine</strong> di pendenza $k$ (ad allungamento nullo la forza è nulla). Se il grafico cessa di essere rettilineo, si è superato il limite di elasticità."},
      {q:"Una forza di $6$ N agisce su una molla con $k=120$ N/m. Di quanti metri si deforma?", tipo:"aperta", num:{v:0.05,u:"m",tol:0.001}, sol:["0,05","0.05"],
       spieg:"Formula inversa: $x=\\dfrac{F}{k}=\\dfrac{6}{120}=0{,}05$ m, cioè $5$ cm. Osserva la coerenza con la proporzionalità diretta: essendo $k$ elevata, una forza modesta produce una deformazione piccola."},
      {q:"Il <strong>dinamometro</strong> è uno strumento che misura:", tipo:"scelta",
       opz:["la massa","le forze","la velocità","l'energia"], ok:1,
       spieg:"Misura le <strong>forze</strong>, sfruttando la proporzionalità fra forza e allungamento della molla. Non misura la massa: appendendo lo stesso corpo sulla Luna leggeremmo circa un sesto del valore letto sulla Terra, perché cambia il peso."}
    ]},
    {n:"Livello 2 - Intermedio", d:"Conversioni, molle in serie e parallelo, taratura del dinamometro.", items:[
      {q:"Una molla si allunga di $4$ cm sotto una forza di $2$ N. Quanto vale $k$, in N/m?", tipo:"aperta", num:{v:50,u:"N/m",tol:0.5}, sol:["50","50 N/m"],
       spieg:"Prima la conversione: $4$ cm $=0{,}04$ m. Poi $k=\\dfrac{2}{0{,}04}=50$ N/m. Usando i centimetri si otterrebbe $0{,}5$, un risultato sbagliato di un fattore 100."},
      {q:"La stessa molla ($k=50$ N/m) viene sottoposta a una forza di $5$ N. Di quanti centimetri si allunga?", tipo:"aperta", num:{v:10,u:"cm",tol:0.1}, sol:["10","10 cm"],
       spieg:"$x=\\dfrac{5}{50}=0{,}1$ m $=10$ cm. Coerente con la proporzionalità diretta: la forza è 2,5 volte quella iniziale, e l'allungamento passa da 4 a 10 cm."},
      {q:"Appendendo una massa di $1{,}2$ kg, una molla si allunga di $6$ cm. Quanto vale $k$, in N/m? ($g=9{,}8$)", tipo:"aperta", num:{v:196,u:"N/m",tol:1}, sol:["196","196 N/m"],
       spieg:"Il peso è $F=mg=1{,}2\\cdot 9{,}8=11{,}76$ N; l'allungamento è $0{,}06$ m. Quindi $k=\\dfrac{11{,}76}{0{,}06}=196$ N/m."},
      {q:"Che cosa accade se si supera il limite di elasticità di una molla?", tipo:"scelta",
       opz:["la costante elastica raddoppia","la molla non torna più alla lunghezza iniziale","la legge di Hooke diventa più precisa","la molla diventa più rigida"], ok:1,
       spieg:"Oltre il limite di elasticità la deformazione diventa <strong>plastica</strong>: la molla resta permanentemente deformata e la legge di Hooke non è più valida (il grafico $F$-$x$ smette di essere rettilineo). Oltre il carico di rottura, si spezza."},
      {q:"Una molla con $k=400$ N/m viene allungata di $2{,}5$ cm. Quanto vale la forza, in newton?", tipo:"aperta", num:{v:10,u:"N",tol:0.05}, sol:["10","10 N"],
       spieg:"Converto: $2{,}5$ cm $=0{,}025$ m. Poi $F=400\\cdot 0{,}025=10$ N."},
      {q:"Due molle identiche con $k=100$ N/m sono collegate in <strong>parallelo</strong>. Quanto vale la costante equivalente, in N/m?", tipo:"aperta", num:{v:200,u:"N/m",tol:0.5}, sol:["200","200 N/m"],
       spieg:"In parallelo le costanti si sommano: $k_{eq}=100+100=200$ N/m. Il sistema è <strong>più rigido</strong>, perché le due molle si spartiscono il carico e a parità di forza si allungano metà."},
      {q:"Le stesse due molle ($k=100$ N/m ciascuna) sono collegate in <strong>serie</strong>. Quanto vale la costante equivalente, in N/m?", tipo:"aperta", num:{v:50,u:"N/m",tol:0.5}, sol:["50","50 N/m"],
       spieg:"In serie si sommano i reciproci: $\\dfrac{1}{k_{eq}}=\\dfrac{1}{100}+\\dfrac{1}{100}=\\dfrac{2}{100}$, quindi $k_{eq}=50$ N/m. Il sistema è <strong>più cedevole</strong>: la stessa forza attraversa entrambe le molle e gli allungamenti si sommano."},
      {q:"Fra la forza elastica e l'allungamento di una molla esiste una proporzionalità:", tipo:"scelta",
       opz:["inversa","diretta","quadratica","nessuna"], ok:1,
       spieg:"<strong>Diretta</strong>: $F=kx$ ha la forma $y=kx$, con la costante elastica nel ruolo di costante di proporzionalità. È l'<em>energia</em> elastica, invece, a dipendere dal quadrato dell'allungamento."},
      {q:"Una molla con $k=300$ N/m viene compressa di $0{,}04$ m. Quanto vale il modulo della forza elastica, in newton?", tipo:"aperta", num:{v:12,u:"N",tol:0.01}, sol:["12","12 N"],
       spieg:"La legge vale anche in compressione: $F=300\\cdot 0{,}04=12$ N. Cambia solo il verso della forza, che ora spinge verso l'esterno anziché tirare verso l'interno."},
      {q:"Un dinamometro ha portata $20$ N e monta una molla con $k=500$ N/m. Qual è il massimo allungamento, in metri?", tipo:"aperta", num:{v:0.04,u:"m",tol:0.001}, sol:["0,04","0.04"],
       spieg:"$x=\\dfrac{F_{max}}{k}=\\dfrac{20}{500}=0{,}04$ m, cioè $4$ cm: è la lunghezza utile della scala graduata dello strumento."}
    ]},
    {n:"Livello 3 - Avanzato", d:"Energia elastica, formule inverse, ragionamenti sul comportamento delle molle.", items:[
      {q:"Una molla con $k=200$ N/m è allungata di $0{,}1$ m. Quanta energia elastica immagazzina, in joule?", tipo:"aperta", num:{v:1,u:"J",tol:0.01}, sol:["1","1 J"],
       spieg:"$E=\\tfrac{1}{2}kx^2=\\tfrac{1}{2}\\cdot 200\\cdot 0{,}01=1$ J. Attenzione a elevare al quadrato <em>solo</em> l'allungamento: $x^2=0{,}01$, non $0{,}1$."},
      {q:"A una molla con $k=160$ N/m si appende una massa di $0{,}8$ kg. Di quanti metri si allunga? ($g=9{,}8$)", tipo:"aperta", num:{v:0.049,u:"m",tol:0.001}, sol:["0,049","0.049"],
       spieg:"$x=\\dfrac{mg}{k}=\\dfrac{0{,}8\\cdot 9{,}8}{160}=\\dfrac{7{,}84}{160}=0{,}049$ m."},
      {q:"Dal grafico $F$-$x$ di una molla si legge che a $x=0{,}03$ m corrisponde $F=9$ N. Quanto vale $k$, in N/m?", tipo:"aperta", num:{v:300,u:"N/m",tol:1}, sol:["300","300 N/m"],
       spieg:"La costante elastica è la <strong>pendenza</strong> della retta: $k=\\dfrac{\\Delta F}{\\Delta x}=\\dfrac{9}{0{,}03}=300$ N/m. Poiché la retta passa per l'origine, basta un solo punto per determinarla."},
      {q:"Una massa di $200$ g allunga una molla di $2$ cm. Di quanti centimetri la allunga una massa di $350$ g?", tipo:"aperta", num:{v:3.5,u:"cm",tol:0.05}, sol:["3,5","3.5","3,5 cm"],
       spieg:"Peso e allungamento sono direttamente proporzionali, quindi basta la proporzione $200:2=350:x$, da cui $x=3{,}5$ cm. Non serve nemmeno calcolare $k$ né convertire le unità: il rapporto si conserva."},
      {q:"Se si taglia una molla esattamente a metà, ciascuna metà ha costante elastica:", tipo:"scelta",
       opz:["dimezzata","uguale","doppia","quadrupla"], ok:2,
       spieg:"La molla intera equivale a due mezze molle <strong>in serie</strong>: $\\dfrac{1}{k}=\\dfrac{1}{k'}+\\dfrac{1}{k'}$, quindi $k'=2k$. Meno spire significa meno cedevolezza: la mezza molla è il doppio più rigida."},
      {q:"Una molla con $k=250$ N/m immagazzina $0{,}5$ J di energia elastica. Di quanti metri è deformata?", tipo:"aperta", num:{v:0.0632,u:"m",tol:0.002}, sol:["0,063","0.063","0,0632"],
       spieg:"Da $E=\\tfrac{1}{2}kx^2$ si ricava $x=\\sqrt{\\dfrac{2E}{k}}=\\sqrt{\\dfrac{1}{250}}=\\sqrt{0{,}004}\\approx 0{,}063$ m, cioè circa $6{,}3$ cm."},
      {q:"La forza elastica viene detta forza di <strong>richiamo</strong> perché:", tipo:"scelta",
       opz:["è molto intensa","tende sempre a riportare il corpo nella posizione di equilibrio","agisce solo sulle molle metalliche","richiama altre forze"], ok:1,
       spieg:"Qualunque sia il verso della deformazione, la forza elastica punta verso la posizione di riposo. È proprio questa proprietà a generare le oscillazioni: superata l'equilibrio per inerzia, la forza cambia verso e frena il corpo - il <em>moto armonico</em>."},
      {q:"Una molla con $k=100$ N/m è allungata di $0{,}15$ m e collegata a un corpo di $2$ kg su un piano liscio. Qual è l'accelerazione del corpo al momento del rilascio, in m/s$^2$?", tipo:"aperta", num:{v:7.5,u:"m/s^2",tol:0.05}, sol:["7,5","7.5"],
       spieg:"Forza elastica: $F=100\\cdot 0{,}15=15$ N. Secondo principio: $a=\\dfrac{F}{m}=\\dfrac{15}{2}=7{,}5$ m/s$^2$. Nota che l'accelerazione non resta costante: man mano che la molla si accorcia la forza cala, ed è proprio questo a rendere il moto armonico anziché uniformemente accelerato."},
      {q:"Due molle, A con $k=120$ N/m e B con $k=300$ N/m, sono sottoposte alla stessa forza. Quale si allunga di più?", tipo:"scelta",
       opz:["la molla A","la molla B","si allungano ugualmente","dipende dalla massa"], ok:0,
       spieg:"Da $x=F/k$ si vede che a parità di forza l'allungamento è <strong>inversamente proporzionale</strong> a $k$: la molla con costante minore (A) si deforma di più. Una $k$ piccola indica una molla morbida."},
      {q:"Raddoppiando l'allungamento di una molla, l'energia elastica immagazzinata:", tipo:"scelta",
       opz:["raddoppia","quadruplica","resta uguale","si dimezza"], ok:1,
       spieg:"$E=\\tfrac{1}{2}kx^2$ dipende dal <strong>quadrato</strong> dell'allungamento: raddoppiando $x$ l'energia diventa quattro volte più grande. La forza, invece, raddoppia soltanto: è solo l'energia ad avere andamento quadratico."}
    ]}
  ]
},

/* ---------------------------------------------------------------- 4 */
{
  id: "fis1-leve",
  titolo: "Leve e macchine semplici",
  sommario: "Fulcro, bracci, forza motrice e resistente: come le leve permettono di equilibrare o trasformare una forza.",
  pillole: [
    {t:"La leva", c:"Una <strong>leva</strong> è un'asta rigida che può ruotare attorno a un punto fisso, il <strong>fulcro</strong>. Su di essa agiscono una forza <strong>motrice</strong> $F_m$ (quella che applichiamo) e una forza <strong>resistente</strong> $F_r$ (il carico da vincere)."},
    {t:"Braccio e momento", c:"Il <strong>braccio</strong> $b$ è la distanza <em>perpendicolare</em> fra il fulcro e la retta d'azione della forza. L'effetto rotatorio di una forza si chiama <strong>momento</strong>: $M=F\,b$. Stessa forza, braccio maggiore = rotazione più efficace."},
    {t:"Equilibrio", c:"Una leva è in equilibrio quando i momenti che la fanno ruotare nei due versi si compensano: $F_m b_m=F_r b_r$. Non si confrontano quindi solo le forze: conta anche <em>dove</em> sono applicate."},
    {t:"Leve di primo genere", c:"Nelle leve di <strong>primo genere</strong> il fulcro sta fra forza motrice e resistente: altalena, forbici, pinze. Possono essere vantaggiose, svantaggiose o indifferenti, secondo i bracci."},
    {t:"Leve di secondo e terzo genere", c:"Nelle leve di <strong>secondo genere</strong> la resistenza è fra fulcro e forza motrice: carriola e schiaccianoci; sono vantaggiose. Nelle leve di <strong>terzo genere</strong> la forza motrice è fra fulcro e resistenza: avambraccio con bicipite e pinzette; sono svantaggiose in forza ma danno velocità e precisione."},
    {t:"Vantaggio meccanico", c:"Il <strong>vantaggio meccanico</strong> è $V=\dfrac{F_r}{F_m}=\dfrac{b_m}{b_r}$. Se è maggiore di 1, basta una forza motrice minore della resistenza; in cambio la mano percorre una distanza maggiore del carico."},
    {t:"La regola pratica", c:"Per svitare un dado o spostare un carico, applica la forza più <strong>lontano</strong> possibile dal fulcro e in direzione <strong>perpendicolare</strong> alla leva: così il braccio è massimo e serve meno forza."}
  ],
  formule: [
    {n:"Momento di una forza", f:"M=F\,b \qquad [\mathrm{N\,m}]"},
    {n:"Equilibrio della leva", f:"F_m b_m=F_r b_r"},
    {n:"Forza motrice", f:"F_m=\frac{F_r b_r}{b_m}"},
    {n:"Vantaggio meccanico", f:"V=\frac{F_r}{F_m}=\frac{b_m}{b_r}"}
  ],
  esempi: [
    {t:"Una carriola solleva un carico di $300$ N posto a $0{,}20$ m dalla ruota. I manici distano $0{,}80$ m dalla ruota. Quale forza verticale serve?", passi:["La ruota è il fulcro; il carico è la resistenza e le mani applicano la forza motrice.","All'equilibrio: $F_m\cdot0{,}80=300\cdot0{,}20$.","Quindi $F_m=60:0{,}80$."], r:"$F_m=75$ N: la carriola è una leva vantaggiosa."},
    {t:"Per aprire una porta spingi con $20$ N vicino alla maniglia, a $0{,}90$ m dai cardini. Qual è il momento della forza?", passi:["I cardini sono il fulcro.","La spinta è perpendicolare alla porta, quindi il braccio è $0{,}90$ m.","$M=F\,b=20\cdot0{,}90$."], r:"$M=18$ N m."}
  ],
  risorse: [
    {t:"Leve: definizioni, tipi ed equilibrio", u:"https://www.youmath.it/lezioni/fisica/dinamica/2964-leve.html", f:"YouMath"},
    {t:"Le macchine semplici e le leve", u:"https://www.edutecnica.it/meccanica/statica/statica.htm", f:"Edutecnica"}
  ],
  livelli: [
    {n:"Livello 1 - Base", d:"Elementi della leva, tipi e momento di una forza.", items:[
      {q:"Il punto attorno al quale una leva può ruotare si chiama:",tipo:"scelta",opz:["braccio","fulcro","resistenza","momento"],ok:1,spieg:"Il <strong>fulcro</strong> è il punto o asse di rotazione della leva."},
      {q:"Il braccio di una forza è:",tipo:"scelta",opz:["la lunghezza totale dell'asta","la distanza perpendicolare fra fulcro e retta d'azione della forza","la forza applicata","la distanza fra le due forze"],ok:1,spieg:"Conta la distanza <strong>perpendicolare</strong> dalla retta d'azione della forza al fulcro."},
      {q:"Una forza di $10$ N applicata con braccio $0{,}5$ m produce un momento di quanti N m?",tipo:"aperta",num:{v:5,u:"N m",tol:0.01},sol:["5","5 Nm"],spieg:"$M=F b=10\cdot0{,}5=5$ N m."},
      {q:"In una leva di primo genere il fulcro si trova:",tipo:"scelta",opz:["fra motrice e resistente","vicino alla resistenza","vicino alla motrice","fuori dalla leva"],ok:0,spieg:"Nella leva di primo genere il fulcro è posto fra le due forze, come nelle forbici."},
      {q:"La carriola è una leva di:",tipo:"scelta",opz:["primo genere","secondo genere","terzo genere","nessun genere"],ok:1,spieg:"Ruota = fulcro, carico = resistenza intermedia, mani = forza motrice: è di secondo genere."},
      {q:"Lo schiaccianoci è normalmente una leva di:",tipo:"scelta",opz:["primo genere","secondo genere","terzo genere","nessun genere"],ok:1,spieg:"Il guscio (resistenza) sta fra cerniera e mano: leva di secondo genere."},
      {q:"Per aumentare il momento di una stessa forza conviene applicarla:",tipo:"scelta",opz:["più vicina al fulcro","più lontana dal fulcro","parallelamente alla leva","verso il fulcro"],ok:1,spieg:"A parità di forza, $M=Fb$: aumentando il braccio aumenta il momento."},
      {q:"Una chiave lunga $0{,}30$ m viene spinta perpendicolarmente con $40$ N. Momento?",tipo:"aperta",num:{v:12,u:"N m",tol:0.01},sol:["12","12 Nm"],spieg:"$M=40\cdot0{,}30=12$ N m."},
      {q:"Nell'avambraccio sollevato dal bicipite, il bicipite applica la forza fra gomito e mano: è una leva di:",tipo:"scelta",opz:["primo genere","secondo genere","terzo genere","non è una leva"],ok:2,spieg:"Il gomito è il fulcro, il bicipite è fra fulcro e carico in mano: terzo genere."},
      {q:"L'unità di misura del momento di una forza è:",tipo:"scelta",opz:["N/m","N m","J/s","kg m"],ok:1,spieg:"Il momento è forza per braccio, quindi si misura in <strong>N m</strong>. Ha stessa unità del joule ma non è energia."}
    ]},
    {n:"Livello 2 - Intermedio", d:"Equilibrio e calcoli con forza motrice, resistenza e bracci.", items:[
      {q:"Una resistenza di $120$ N è a $0{,}20$ m dal fulcro; la forza motrice agisce a $0{,}60$ m. Quale forza motrice equilibra la leva?",tipo:"aperta",num:{v:40,u:"N",tol:0.01},sol:["40","40 N"],spieg:"$F_m=120\cdot0{,}20/0{,}60=40$ N."},
      {q:"Se in una leva $F_m=30$ N, $b_m=0{,}8$ m e $b_r=0{,}2$ m, qual è la resistenza equilibrata?",tipo:"aperta",num:{v:120,u:"N",tol:0.01},sol:["120","120 N"],spieg:"$F_r=F_m b_m/b_r=30\cdot0{,}8/0{,}2=120$ N."},
      {q:"Una leva ha braccio motore $1$ m e braccio resistente $0{,}25$ m. Il vantaggio meccanico vale:",tipo:"aperta",num:{v:4,tol:0.01},sol:["4"],spieg:"$V=b_m/b_r=1/0{,}25=4$. La resistenza può essere quattro volte la forza motrice."},
      {q:"Se $b_m=b_r$, una leva è:",tipo:"scelta",opz:["vantaggiosa","svantaggiosa","indifferente","impossibile"],ok:2,spieg:"Bracci uguali implicano $F_m=F_r$: non si guadagna né si perde forza."},
      {q:"Una forza di $50$ N agisce con braccio $0{,}4$ m. Quale forza con braccio $0{,}2$ m la equilibra?",tipo:"aperta",num:{v:100,u:"N",tol:0.01},sol:["100","100 N"],spieg:"I momenti devono essere uguali: $50\cdot0{,}4=F\cdot0{,}2$, dunque $F=100$ N."},
      {q:"Quale leva è sicuramente vantaggiosa in forza?",tipo:"scelta",opz:["carriola","avambraccio","pinzetta","forbici con bracci uguali"],ok:0,spieg:"La carriola è di secondo genere e ha il braccio motore maggiore del resistente."},
      {q:"Una porta è più facile da aprire spingendo:",tipo:"scelta",opz:["vicino ai cardini","a metà porta","sulla maniglia","parallelamente alla porta"],ok:2,spieg:"La maniglia è lontana dai cardini: massimizza il braccio e quindi il momento."},
      {q:"Una leva con $F_r=200$ N, $b_r=0{,}15$ m e $F_m=50$ N richiede un braccio motore di quanti metri?",tipo:"aperta",num:{v:0.6,u:"m",tol:0.01},sol:["0,6","0.6"],spieg:"$b_m=F_r b_r/F_m=200\cdot0{,}15/50=0{,}60$ m."},
      {q:"Se il braccio motore raddoppia mentre tutto il resto resta uguale, la forza motrice necessaria:",tipo:"scelta",opz:["raddoppia","si dimezza","resta uguale","quadruplica"],ok:1,spieg:"Da $F_m=F_r b_r/b_m$, la forza è inversamente proporzionale al braccio motore."},
      {q:"Un'altalena ha due bambini: $300$ N a $1$ m da un lato. A che distanza deve sedersi un bambino di $500$ N dall'altro lato?",tipo:"aperta",num:{v:0.6,u:"m",tol:0.01},sol:["0,6","0.6"],spieg:"$300\cdot1=500\cdot b$, quindi $b=0{,}60$ m."}
    ]},
    {n:"Livello 3 - Avanzato", d:"Problemi applicati, versi dei momenti e vantaggio meccanico.", items:[
      {q:"Una carriola porta $480$ N di carico a $0{,}25$ m dalla ruota. Le mani sono a $1$ m. Forza totale alle mani?",tipo:"aperta",num:{v:120,u:"N",tol:0.01},sol:["120","120 N"],spieg:"$F_m\cdot1=480\cdot0{,}25=120$, quindi servono 120 N."},
      {q:"Una chiave da $0{,}25$ m deve produrre un momento di $50$ N m. Forza perpendicolare necessaria?",tipo:"aperta",num:{v:200,u:"N",tol:0.01},sol:["200","200 N"],spieg:"$F=M/b=50/0{,}25=200$ N."},
      {q:"Per ottenere lo stesso momento con una chiave doppia, la forza richiesta:",tipo:"scelta",opz:["raddoppia","si dimezza","resta uguale","diventa zero"],ok:1,spieg:"Momento fisso: $F=M/b$. Se il braccio raddoppia, la forza si dimezza."},
      {q:"Una leva ha vantaggio meccanico $5$ e deve vincere $750$ N. Forza motrice ideale?",tipo:"aperta",num:{v:150,u:"N",tol:0.01},sol:["150","150 N"],spieg:"$V=F_r/F_m$, quindi $F_m=750/5=150$ N."},
      {q:"Le pinzette sono svantaggiose in forza ma utili perché:",tipo:"scelta",opz:["eliminano il fulcro","danno grande spostamento e precisione all'estremità","aumentano il peso","non hanno resistenza"],ok:1,spieg:"Le leve di terzo genere sacrificano forza per velocità, ampiezza di movimento e controllo."},
      {q:"Una forza di $80$ N applicata a $30°$ rispetto a una chiave è meno efficace che a $90°$ perché:",tipo:"scelta",opz:["il braccio perpendicolare è minore","la massa cambia","il fulcro sparisce","il momento non dipende dall'angolo"],ok:0,spieg:"Conta la componente perpendicolare: spingere a 90° massimizza il braccio efficace."},
      {q:"Una leva è in equilibrio con $F_m=75$ N e $b_m=0{,}8$ m; la resistenza è $300$ N. Quanto vale $b_r$?",tipo:"aperta",num:{v:0.2,u:"m",tol:0.01},sol:["0,2","0.20"],spieg:"$b_r=F_m b_m/F_r=75\cdot0{,}8/300=0{,}20$ m."},
      {q:"Una forza motrice di $60$ N con braccio $0{,}5$ m equilibra una resistenza di $150$ N. Braccio resistente?",tipo:"aperta",num:{v:0.2,u:"m",tol:0.01},sol:["0,2","0.20"],spieg:"$b_r=60\cdot0{,}5/150=0{,}20$ m."},
      {q:"In una leva ideale vantaggiosa in forza, il carico rispetto alla mano percorre:",tipo:"scelta",opz:["una distanza maggiore","la stessa distanza","una distanza minore","nessuna distanza"],ok:2,spieg:"Si conserva il lavoro: guadagnare forza significa muovere la mano per una distanza maggiore del carico."},
      {q:"Un meccanico applica $150$ N a $0{,}40$ m dal fulcro. Il momento vale:",tipo:"aperta",num:{v:60,u:"N m",tol:0.01},sol:["60","60 Nm"],spieg:"$M=150\cdot0{,}40=60$ N m."}
    ]}
  ]
},
];
